name: YeasyBasics
version: 1.0.0
main: com.gmail.perhapsitisyeazz.yeasybasics.YeasyBasics
api-version: '1.15'
description: 'Friend plugin'
author: 'YeaZz_'
commands:
  gamemode:
    description: Allows you to change your gamemode
    permission: gamemode
    permission-message: You do not have the permission to use this command.
    usage: /<command>
    aliases:
      - gm